package tw.foxo.boise.upost.networkHandler

import okhttp3.MediaType

val JSON = MediaType.parse("application/json; charset=utf-8")

// usls
private var BASENETWORK = "https://upost.foxo.tw/"
val BOARDURL = BASENETWORK + "api/post/b/"
val LOGIN_URL = BASENETWORK + "api/user/login"
val POST_LIST_URL = BASENETWORK + "api/post/p/"
val USER_INFO_URL = BASENETWORK + "api/user/info"
val REG_URL = BASENETWORK + "api/user/register"
val CREATE_URL = BASENETWORK + "api/user/create"
val COMMENT_HEAD = BASENETWORK + "api/post/c/"
val C_COMMINT_END = "create"
val SORT_BY_DATE = "?sort_by=date"
val E_LIKE = "like"
val E_UNLIKE = "unlike"
val DEL = "del"
val EDIT = "edit"

// tags
val USERNAME = "username"
val PASSWORD = "password"
val NETWORKERROR = "Oops network are not good"
val BOARDID = "board_id"
val BOARDNAME = "board_name"
val ISSCHOOLBOARD = "isSchoolBoard"
val B_MYSCHOOL = "myschool"
val B_BOARD = "boards"
val B_SCHOOL = "school"
val P_POST = "posts"
val POST = "post"
val AUTHOR = "author"
val AUTHOR_SEX = "author_sex"
val LIKE = "like"
val POST_CONTEXT = "text"
val COMMIT_CONTEXT = "text"
val TITLE = "title"
val CREATEDATE = "create_date"
val POSTID = "post_id"
val ISLIKE = "is_like"
val COMMITNUM = "commit_num"
val BOY = "male"
val GIRL = "female"
val EMAIL = "email"
val BOY_ICON = "#488EBB"
val GIRL_ICON = "#BC466B"
val OTHER_ICON = "#4B4848"
val SEX = "sex"
val MSG = "message"
val TOKEN = "token"
val COMMITID = "commit_id"
val ISDEL = "is_del"
val COMMIT = "commit"
val COMMIT_TOP = "top_commit"
val ISAUTHOR = "is_author"

